### ISSUE TITLE
Banding and discoloration 

### ISSUE THREAD

**Issue by RoninKnox** [BruceKnowsHow/Ebin-Shaders#1]
The last few releases have had odd banding in the sky and extreme discoloration of blocks underground for me.

Nvidia gt 940m
Driver: 368.69
![2016-07-11_14 05 54](https://cloud.githubusercontent.com/assets/19658446/16746747/a3310f0e-4770-11e6-85d6-2ab0681a4067.png)
![2016-07-11_14 05 59](https://cloud.githubusercontent.com/assets/19658446/16746748/a3313092-4770-11e6-81e2-6eae8c1d78d6.png)

**Comment by BruceKnowsHow** [comment]
I'm guessing you're using an older version of Optifine. Optifine 1.10.2_HD_U_C1 added more efficient color buffer formats. If you're using an Optifine without the new formats, it will revert to using 8-bit formats, which will cause the banding you're seeing.

There are currently no 1.9 versions of Optifine that will not have this issue.

**Comment by RoninKnox** [comment]
Thank you that solved my problem!
