### ISSUE TITLE
Indoor/underground blocks appear reflective during rain.

### ISSUE THREAD

**Issue by GTD-Carthage** [BruceKnowsHow/Ebin-Shaders#13]
I am currently playing on Minecraft 1.10.2, specifically, the All the Mods modpack available via Curse. I am relying on Optifine 1.10.2 HD_U_D2 for my shader effects and overall performance has actually been quite stellar - I'm virtually playing with Ebin Shaders all the time! (I have a GTX 870M system)

However, I get a huge visual glitch when a rain or a storm is triggered - apparently, all blocks, regardless of what they are or where they are, become overly reflective.

Sample images:

* Within my underground base:
http://puu.sh/sqDI0/b53d4b4159.jpg
* On the surface - it's a bit difficult to distinguish blocks due to the crazy reflections:
http://puu.sh/sqDSZ/414977f3c5.jpg <- Note also, the sky is completely bright - are there effects intended for rain at the moment or none at all?
* The problem persists even in the mine shafts at level Y:17
http://puu.sh/sqDXB/cbd1efb9b7.jpg

At minimum, is there a way to turn off reflection on non-water blocks for now?

**Comment by dotModded** [comment]
So I can fix the underground things however the sky staying won't be fixed for a while. And you can turn off specular maps under shader options/setup and turn off specular map texture pack

**Comment by GTD-Carthage** [comment]
Are specular maps the ones being used for block shininess?

I've turned off both Specular Map from the Optifine shader options and the Shader Options (Shader Options --> Setup --> Specular Map Texture Pack: OFF) itself but the blocks are still fully reflective. :(

**Comment by ajthemacboy** [comment]
I'd like to add that animals are also reflective, which I think it unrealistic in any weather.

**Comment by iykHvfIvfR** [comment]
Fixed by https://github.com/BruceKnowsHow/Ebin-Shaders/commit/9a2c57d00c0e11a70b46f0435937c63787000562

**Comment by nzcv** [comment]
Fixed by https://github.com/BruceKnowsHow/Ebin-Shaders/commit/9a2c57d00c0e11a70b46f0435937c63787000562
