### ISSUE TITLE
Ebin shaders not working

### ISSUE THREAD

**Issue by AutoClick2K17** [BruceKnowsHow/Ebin-Shaders#19]
I downloaded the zip file and put it in the shader pack folder. I open Minecraft and select ebin shaders. The only problem is, that it still stays at the default texture. when I go into shader options, there's nothing there. Please help me.

Thanks.

**Comment by McHox** [comment]
Folder Structure

It should be either:

Ebin-Shaders/shaders/(.vsh & .fsh files)
or:

Ebin-Shaders.zip/shaders/(.vsh & .fsh files)
If you download it from GitHub, it will be:

Ebin-Shaders.zip/Ebin-Shaders/shaders/(.vsh & .fsh files)

**Comment by AutoClick2K17** [comment]
it's not

**Comment by AutoClick2K17** [comment]
i don't know why

**Comment by McHox** [comment]
what do you mean it's not?

**Comment by AutoClick2K17** [comment]
I don't know

**Comment by McHox** [comment]
if the folder structure is not as shown in the 2 examples above then you have to change it manually of course

**Comment by AutoClick2K17** [comment]
k

**Comment by AutoClick2K17** [comment]
like how?

**Comment by McHox** [comment]
you extract the zip m8
thats it

**Comment by AutoClick2K17** [comment]
heres the zip
[Ebin-Shaders-master-a3ce88e602193e72b674b56c229d55bff8f200b5 (2).zip](https://github.com/BruceKnowsHow/Ebin-Shaders/files/949268/Ebin-Shaders-master-a3ce88e602193e72b674b56c229d55bff8f200b5.2.zip)

**Comment by McHox** [comment]
i don't need the zip m8
just in case you have downloaded the wrong version or got something mixed up:
https://github.com/BruceKnowsHow/Ebin-Shaders/archive/master.zip

**Comment by AutoClick2K17** [comment]
I downloaded it on the ebin website

**Comment by McHox** [comment]
that doesnt matter,its the same folder structure.
now fi you could do me a favor and do what i told you,it will work
extract the folder from the zip and place the folder into the shaderpacks folder

**Comment by AutoClick2K17** [comment]
k it worked! thx
