### ISSUE TITLE
Separation of Double Tallgrass

### ISSUE THREAD

**Issue by luna810** [BruceKnowsHow/Ebin-Shaders#2]
Nvidia GTX 980 ti
Driver: 364.72
![2016-07-16_20 28 33](https://cloud.githubusercontent.com/assets/20489635/16894537/3bab1172-4b94-11e6-8a0b-ad2e854d390e.png)

**Comment by dotModded** [comment]
This is technically impossible to fix, you would just need to turn it off at that point.

**Comment by BruceKnowsHow** [comment]
I didn't realize tall grass had a waving effect, we'll probably turn it off, otherwise we'll need some convoluted help from Optifine.

**Comment by luna810** [comment]
Thank you reply!
