### ISSUE TITLE
caves are not dark at all

### ISSUE THREAD

**Issue by soraphis** [BruceKnowsHow/Ebin-Shaders#21]
if i tweak with the exposure it just makes the game dark and moody if i'm outside

reference screenshots:

**without shader**
![2017-05-03_00 46 45](https://cloud.githubusercontent.com/assets/3066582/25642441/1b640474-2f9a-11e7-984e-6ee6f916d088.png)

**with shader**
![2017-05-03_00 46 25](https://cloud.githubusercontent.com/assets/3066582/25642438/18122b8e-2f9a-11e7-9a99-8a7ce82bb894.png)

**Comment by McHox** [comment]
Can confirm, not achievable with ingame shader settings as far as I know

**Comment by BruceKnowsHow** [comment]
Accidentally left the lights on while working on caustics. Fixed in the newest update.

**Comment by birdspider** [comment]
I'll try it when I get home, but does this effect non-caves i.e. nights outdoor (#20) ?
