### ISSUE TITLE
add proper ozone distribution

### ISSUE THREAD

**Issue by MathGeniusJodie** [BruceKnowsHow/Ebin-Shaders#24]
http://skyrenderer.blogspot.ca/2012/10/vertical-distribution-of-ozone.html?m=1

u skrub

**Comment by MathGeniusJodie** [comment]
<3

**Comment by BruceKnowsHow** [comment]
I think it would require approximating this function inside the loop:
https://1.bp.blogspot.com/-wCcc390laf4/UIduZZiOjdI/AAAAAAAAArc/dukakDUYMg4/s1600/ozone_concentration_graph.gif

It will definitely be complicated, very slow compared to how I've optimized the function so far, and will probably offer only minimal visual improvements. Not planned.

**Comment by McHox** [comment]
Aww

**Comment by MathGeniusJodie** [comment]
:(

**Comment by McHox** [comment]
neeeeeeearrrdd

**Comment by MathGeniusJodie** [comment]
thanks ^^

**Comment by BruceKnowsHow** [comment]
Please don't shitpost in here or I will turn off E-mail notifications
