### ISSUE TITLE
Pom deformation

### ISSUE THREAD

**Issue by McHox** [BruceKnowsHow/Ebin-Shaders#27]
http://imgur.com/a/xS0zm
 ingame settings don't seem to affect it
has been there for a while,so idk when it started to act up

```
latest master version
mc version: 1.11.2
OptiFine 1.11.2 HD_U_C1_pre

system:
4790k - 16gb 2400mhz ddr3 - 1080 ti
```

**Comment by BruceKnowsHow** [comment]
Should be fixed in the latest update
