### ISSUE TITLE
My computer doesn't support the "shadow" program

### ISSUE THREAD

**Issue by noblereign** [BruceKnowsHow/Ebin-Shaders#29]
When I enabled it, i got this: 
![image](https://cloud.githubusercontent.com/assets/2935979/26756500/bc629184-4858-11e7-99aa-c8af0e8450b3.png)

and then this is happening:

![image](https://cloud.githubusercontent.com/assets/2935979/26756502/cbfe40ac-4858-11e7-9169-2738f278f19b.png)

basically the whole world gets filled with shadows as i walk through it.

**Comment by McHox** [comment]
Got what?

**Comment by noblereign** [comment]
sorry i just edited it because apparently CTRL + ENTER is post

**Comment by BruceKnowsHow** [comment]
![5r12f4](https://cloud.githubusercontent.com/assets/17636733/26759127/22a18fee-48aa-11e7-9172-192e57f371aa.png)

**Comment by BruceKnowsHow** [comment]
This was probably fixed by the newest update, though I can't be certain since you never posted a crash report.

**Comment by noblereign** [comment]
Yay! It's fixed!
