### ISSUE TITLE
PBR artifacts

### ISSUE THREAD

**Issue by Cineminecraft** [BruceKnowsHow/Ebin-Shaders#4]
I wanted to check out PBR after the stream but I have some weird flickering artifacts. brown on block in middle, black on left block
GTX980 TI
driver: 368.81
v1.10.2 w/ optifine HD_U_C2
![2016-08-22_13 18 14](https://cloud.githubusercontent.com/assets/13148927/17853161/37c5408e-686b-11e6-991d-c0efc5810316.png)
When can we expect to have a PBR pack that works with Ebin? I believe joey said he'd put a pulchra test version up on github.

**Comment by McHox** [comment]
did you enable pbr resource pack in the shadersettings?

**Comment by Cineminecraft** [comment]
yes I did

**Comment by dotModded** [comment]
So the previous texturepacks are supported, just they won't look right, and I'll look into that artifact

**Comment by dotModded** [comment]
Is this still an issue?
