### ISSUE TITLE
Invalid Program

### ISSUE THREAD

**Issue by Lunchb0ne** [BruceKnowsHow/Ebin-Shaders#8]
Hey guys, I wanted to use this with my GTX 1070 but I keep getting invalid program when loading the shaders.

It displays invalid program for gbuffers_textured, terrain, water,hand and entities

**Comment by McHox** [comment]
Using master or dev branch?

**Comment by McHox** [comment]
Master is broken for me too,try dev branch

**Comment by Lunchb0ne** [comment]
Ok thanks!!

**Comment by dotModded** [comment]
This has been fixed.

**Comment by noob24680** [comment]
where is ebin dev branch shader, there is only master
